export enum SVGRefEnum{
    COINS_HAND = 'coins-shandales',
    SHOPPING_CART = 'shopping-cart',
    WALLET = 'wallet',
    HEARTS = 'hearts',
    GIFT = 'gift',
    BANK_NOTE = 'bank-note',
    CHECK_CIRCLE = 'check-circle',
    MINUS_CIRCLE = 'minus-circle',
    HEART_ROUNDED = 'heart-rounded',
    TRASH = 'trash',
    NULL = 'null',
    USERS = 'users',
    SHOPPING_BAG_2 = 'shopping-bag-2',
    TAG = 'tag',
    LIST = 'list',
    ALERT_TRIANGLE = 'alert-triangle',
    ANNOUNCEMENT = 'announcement'
}